=== denkbares/d3web-Experimental/Research/KnowWE-ObjectType-Generator/src/ObjectTypeHierarchy.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT ObjectTypeHierarchy (ObjectType+)>
<!ELEMENT ObjectType (ChildrenTypes?, CustomRenderer?, (SubtreeHandler|AnonymousSubtreeHandler)*, (CustomSectionFinder | RegExSectionFinder | AllTextSectionFinder))>
<!ATTLIST ObjectType
	ClassName CDATA #REQUIRED
	Extends CDATA #REQUIRED
	Position CDATA #IMPLIED>
<!ELEMENT ChildrenTypes (ObjectType+)>
<!ELEMENT CustomRenderer EMPTY>
<!ATTLIST CustomRenderer
	ClassName CDATA #REQUIRED
	Package CDATA #REQUIRED>
<!ELEMENT SubtreeHandler EMPTY>
<!ATTLIST SubtreeHandler
	ClassName CDATA #REQUIRED
	Package CDATA #REQUIRED>
<!ELEMENT AnonymousSubtreeHandler EMPTY>
<!ATTLIST AnonymousSubtreeHandler
	Name CDATA #REQUIRED
	Extends CDATA #REQUIRED>
<!ELEMENT CustomSectionFinder EMPTY>
<!ATTLIST CustomSectionFinder
	ClassName CDATA #REQUIRED
	Package CDATA #REQUIRED>
<!ELEMENT RegExSectionFinder (RegEx)>
<!ELEMENT RegEx (#PCDATA)>
<!ELEMENT AllTextSectionFinder EMPTY>

=== denkbares/d3web-Experimental/Research/KnowWE-ObjectType-Generator/src/main/resources/examples/TurtleMarkupSimple.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ObjectTypeHierarchy SYSTEM "../dtd/ObjectTypeHierarchy.dtd">
<ObjectTypeHierarchy Author="Sebastian Furth">
	<ObjectType ClassName="TurtleMarkupSimple" SuperType="DefaultKnowWEObjectType">
		<ChildrenTypes>
			<ObjectType ClassName="Subject" SuperType="OWLTermReference" Position="2">
				<RegExSectionFinder>
					<RegEx>...</RegEx>
				</RegExSectionFinder>
			</ObjectType>
			<ObjectType ClassName="Predicate" SuperType="OWLTermReference" Position="1">
				<RegExSectionFinder>
					<RegEx>...</RegEx>
				</RegExSectionFinder>
			</ObjectType>
			<ObjectType ClassName="Object" SuperType="OWLTermReference" Position="3">
				<AllTextSectionFinder/>
			</ObjectType>
		</ChildrenTypes>
		<RegExSectionFinder>
			<RegEx>{(.*?::.*?)}</RegEx>
		</RegExSectionFinder>
		<AnonymousSubtreeHandler Name="TurtleMarkupSimpleSubtreeHandler" SuperType="OWLSubtreeHandler"/>
	</ObjectType>
</ObjectTypeHierarchy>
